version: '3'

services:
  myapp:
    build: .
    environment:
      - CONFIG_PATH=/bin/config/config.yaml
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    # command: ["./wait-for", "postgres:5432", "--", "/bin/main"]

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    command: ["-path", "/migrations", "-database", "postgres://postgres:postgres@postgres:5432/task?sslmode=disable", "up"]
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
